// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component TestCase inherits Window {
    width: 64px;
    height: 64px;
    background: lightblue;

    Path {
        stroke: green;
        stroke-width: 8px;
        commands: "150,15 258,77 258,202 150,265 42,202 42,77 Z";
    }
}
